-- Table structure for table user_details
CREATE TABLE IF NOT EXISTS user_details
(
    user_id varchar(50) NOT NULL,
    pw      char(68)    NOT NULL,
    active  int         NOT NULL,
    PRIMARY KEY (user_id)
);

-- Table structure for table user_roles
CREATE TABLE IF NOT EXISTS user_roles
(
    user_id varchar(50) NOT NULL,
    user_role    varchar(50) NOT NULL,
    CONSTRAINT user_roles_idx_1 UNIQUE (user_id, user_role),
    CONSTRAINT user_roles_user_id_fk FOREIGN KEY (user_id) REFERENCES user_details (user_id)
);

CREATE TABLE IF NOT EXISTS employee
(
    id         bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    first_name varchar(45) DEFAULT NULL,
    last_name  varchar(45) DEFAULT NULL,
    email      varchar(45) DEFAULT NULL,
    CONSTRAINT employee_email_unique_idx UNIQUE (email),
    PRIMARY KEY (id)
);
